import {Geist, Geist_Mono} from "next/font/google";
import {Orbitron} from "next/font/google";
import {Borel} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/app/Header";
import {Menu, X} from "lucide-react"; // Optional: use any icon library

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const borel = Borel({
    weight: "400",
    variable: "--font-borel",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const orbitron = Orbitron({
    variable: "--font-orbitron",
    subsets: ["latin"],
});

export const metadata = {
    title: "Matteo Weber",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    const year = new Date().getFullYear();

    return (
        <html lang="de" className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${borel.variable}`}>
        <body className="antialiased flex flex-col min-h-screen text-gray-800 font-sans">

        <Header></Header>

        <main className="bg-[#FFFFFF]">
            {children}
        </main>

        <footer className="bg-[#dbeafe] text-black mt-auto font-[Geist] border-t border-[#93c5fd]">
            <div className="w-full px-4 py-8 grid grid-cols-1 md:grid-cols-3 items-center gap-6 md:gap-10 text-center">
                <p className="text-sm text-center md:text-left md:justify-self-start">© {year} Matteo Weber. All rights reserved.</p>

                <p className="flex flex-wrap items-center justify-center md:justify-self-center divide-x divide-black">
                Matteo Weber
                </p>

                <div className="flex items-center justify-center gap-3 md:justify-self-end">
                    <a href="https://github.com/mattadosss" target="_blank" rel="noopener noreferrer" aria-label="Open GitHub profile" className="inline-flex items-center gap-2 text-sm hover:underline">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-8 h-8 mr-2">
                            <path d="M12 2C6.477 2 2 6.484 2 12.021c0 4.428 2.865 8.186 6.839 9.504.5.092.682-.217.682-.483 0-.237-.009-.868-.014-1.703-2.782.605-3.369-1.342-3.369-1.342-.454-1.157-1.11-1.465-1.11-1.465-.908-.62.069-.608.069-.608 1.004.07 1.532 1.032 1.532 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.339-2.221-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.025A9.564 9.564 0 0 1 12 6.844c.85.004 1.705.115 2.504.337 1.909-1.295 2.748-1.025 2.748-1.025.546 1.378.202 2.397.1 2.65.64.7 1.028 1.595 1.028 2.688 0 3.847-2.337 4.695-4.566 4.944.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.749 0 .268.18.579.688.481C19.138 20.203 22 16.447 22 12.021 22 6.484 17.523 2 12 2z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </footer>
        </body>
        </html>
    );
}