import {Geist, Geist_Mono} from "next/font/google";
import {Orbitron} from "next/font/google";
import {Borel} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/app/Header";
import {Menu, X} from "lucide-react"; // Optional: use any icon library

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const borel = Borel({
    weight: "400",
    variable: "--font-borel",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const orbitron = Orbitron({
    variable: "--font-orbitron",
    subsets: ["latin"],
});

export const metadata = {
    title: "Matteo Weber",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {

    return (
        <html lang="de" className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${borel.variable}`}>
        <body className="antialiased flex flex-col min-h-screen text-gray-800 font-sans">

        <Header></Header>

        <main className="bg-[#FFFFFF]">
            {children}
        </main>

        <footer className="bg-red-200 text-black p-6 mt-auto font-[Geist]">
            <div className="container mx-auto flex flex-col md:flex-row justify-between items-center">
                <p className="text-sm">© 2025 Matteo Weber. All rights reserved.</p>
                <div className="flex space-x-4 grid grid-cols-3 divide-x-2 divide-black-400">
                    <Link href="/datenschutz" className="pr-3 hover:underline">Datenschutz</Link>
                    <Link href="/impressum" className="hover:underline">Impressum</Link>
                    <Link href="/contact" className="hover:underline">Contact</Link>
                </div>
            </div>
        </footer>
        </body>
        </html>
    );
}